/**
 * Android-specific utilities for Bharat AI SDK
 */

import { Platform } from 'react-native';
import DeviceInfo from 'react-native-device-info';

// Android-specific constants
export const ANDROID_VERSION = Platform.Version as number;
export const IS_ANDROID = Platform.OS === 'android';

// Android-specific features
export const ANDROID_FEATURES = {
  fingerprint: true,
  faceUnlock: true,
  googlePay: true,
  healthConnect: true,
  nearbyConnections: true,
  arCore: true,
  mlKit: true,
  tensorflowLite: true,
  firebase: true,
  googleMaps: true,
  googleSignIn: true,
  inAppUpdates: true,
  inAppReviews: true,
  billing: true,
  location: true,
  camera: true,
  microphone: true,
  storage: true,
  contacts: true,
  calendar: true,
  sms: true,
  phone: true,
  sensors: true,
  nfc: true,
  bluetooth: true,
  wifi: true,
  telephony: true,
  vpn: true,
  print: true,
  sharing: true,
  widgets: true,
  notifications: true,
  backgroundServices: true,
  foregroundServices: true,
  jobScheduler: true,
  workManager: true,
  alarmManager: true,
  powerManager: true,
  batteryManager: true,
  memoryManager: true,
  storageManager: true,
  networkManager: true,
  locationManager: true,
  sensorManager: true,
  cameraManager: true,
  audioManager: true,
  mediaPlayer: true,
  mediaRecorder: true,
  telephonyManager: true,
  subscriptionManager: true,
  smsManager: true,
  bluetoothManager: true,
  wifiManager: true,
  nfcManager: true,
  vibrator: true,
  flashlight: true,
  biometricPrompt: true,
  credentialManager: true,
  keyguardManager: true,
  devicePolicyManager: true,
  appOpsManager: true,
  activityManager: true,
  packageManager: true,
  windowManager: true,
  displayManager: true,
  inputMethodManager: true,
  accessibilityManager: true,
  notificationManager: true,
  accountManager: true,
  downloadManager: true,
  connectivityManager: true,
  nsdManager: true,
  wifiP2pManager: true,
  bluetoothAdapter: true,
  nfcAdapter: true,
  sensorManager: true,
  locationManager: true,
  cameraManager: true,
  audioManager: true,
  telephonyManager: true,
  subscriptionManager: true,
  smsManager: true,
  bluetoothManager: true,
  wifiManager: true,
  nfcManager: true,
  vibrator: true,
  flashlight: true,
  biometricPrompt: true,
  credentialManager: true,
  keyguardManager: true,
  devicePolicyManager: true,
  appOpsManager: true,
  activityManager: true,
  packageManager: true,
  windowManager: true,
  displayManager: true,
  inputMethodManager: true,
  accessibilityManager: true,
  notificationManager: true,
  accountManager: true,
  downloadManager: true,
  connectivityManager: true,
  nsdManager: true,
  wifiP2pManager: true,
};

// Android-specific device capabilities
export async function getAndroidCapabilities() {
  try {
    const model = await DeviceInfo.getModel();
    const brand = await DeviceInfo.getBrand();
    const systemVersion = await DeviceInfo.getSystemVersion();
    const appVersion = DeviceInfo.getVersion();
    const buildNumber = DeviceInfo.getBuildNumber();
    const isTablet = DeviceInfo.isTablet();
    const isEmulator = await DeviceInfo.isEmulator();
    const androidId = await DeviceInfo.getAndroidId();
    const apiLevel = await DeviceInfo.getApiLevel();

    return {
      model,
      brand,
      systemVersion,
      appVersion,
      buildNumber,
      isTablet,
      isEmulator,
      androidId,
      apiLevel,
      features: ANDROID_FEATURES,
      performance: {
        hasNeuralProcessingUnit: apiLevel >= 28, // Android 9.0+
        hasTensorFlowLite: true,
        hasMLKit: true,
        hasARCore: apiLevel >= 24, // Android 7.0+
        has5G: apiLevel >= 29, // Android 10.0+
        hasWiFi6: apiLevel >= 30, // Android 11.0+
        hasBluetooth5: apiLevel >= 28, // Android 9.0+
        hasNFC: true,
        hasFingerprint: true,
        hasFaceUnlock: apiLevel >= 29, // Android 10.0+
        hasGPS: true,
        hasAccelerometer: true,
        hasGyroscope: true,
        hasMagnetometer: true,
        hasLightSensor: true,
        hasProximitySensor: true,
        hasBarometer: true,
        hasTemperatureSensor: true,
        hasHumiditySensor: true,
        hasHeartRateSensor: false, // Device specific
        hasStepCounter: apiLevel >= 19, // Android 4.4+
        hasStepDetector: apiLevel >= 19, // Android 4.4+
        hasGameRotationVector: apiLevel >= 18, // Android 4.3+
        hasGeomagneticRotationVector: apiLevel >= 18, // Android 4.3+
        hasRotationVector: apiLevel >= 9, // Android 2.3+
        hasLinearAcceleration: apiLevel >= 9, // Android 2.3+
        hasGravity: apiLevel >= 9, // Android 2.3+
        hasOrientation: true,
        hasPressure: apiLevel >= 21, // Android 5.0+
        hasRelativeHumidity: apiLevel >= 21, // Android 5.0+
        hasAmbientTemperature: apiLevel >= 21, // Android 5.0+
        hasMagneticFieldUncalibrated: apiLevel >= 18, // Android 4.3+
        hasGyroscopeUncalibrated: apiLevel >= 18, // Android 4.3+
        hasGameRotationVector: apiLevel >= 18, // Android 4.3+
        hasSignificantMotion: apiLevel >= 18, // Android 4.3+
        hasStepDetector: apiLevel >= 19, // Android 4.4+
        hasStepCounter: apiLevel >= 19, // Android 4.4+
        hasGeomagneticRotationVector: apiLevel >= 18, // Android 4.3+
        hasHeartRate: apiLevel >= 20, // Android 4.4W+
        hasPose6dof: apiLevel >= 24, // Android 7.0+
        hasStationaryDetect: apiLevel >= 24, // Android 7.0+
        hasMotionDetect: apiLevel >= 24, // Android 7.0+
        hasHeartBeat: apiLevel >= 26, // Android 8.0+
        hasLowLatencyOffload: apiLevel >= 26, // Android 8.0+
        hasAccelerometerUncalibrated: apiLevel >= 26, // Android 8.0+
        hasHingeAngle: apiLevel >= 29, // Android 10.0+
        hasHeadTracker: apiLevel >= 30, // Android 11.0+
        hasAccelerometerLimitedAxes: apiLevel >= 30, // Android 11.0+
        hasGyroscopeLimitedAxes: apiLevel >= 30, // Android 11.0+
        hasHeading: apiLevel >= 30, // Android 11.0+
        hasCamera: true,
        hasFlash: true,
        hasFrontCamera: true,
        hasRearCamera: true,
        hasMicrophone: true,
        hasSpeaker: true,
        hasVibrator: true,
        hasFlashlight: true,
        hasGPS: true,
        hasNetworkLocation: true,
        hasPassiveLocation: true,
        hasWiFi: true,
        hasBluetooth: true,
        hasNFC: true,
        hasUSB: true,
        hasHDMI: true,
        hasEthernet: true,
        hasVPN: true,
        hasHotspot: true,
        hasTethering: true,
        hasTelephony: true,
        hasSMS: true,
        hasMMS: true,
        hasPhoneCalls: true,
        hasVideoCalls: true,
        hasVoLTE: apiLevel >= 22, // Android 5.1+
        hasVoWiFi: apiLevel >= 27, // Android 8.1+
        has RCS: apiLevel >= 30, // Android 11.0+
        has5G: apiLevel >= 29, // Android 10.0+
        hasWiFi6: apiLevel >= 30, // Android 11.0+
        hasWiFi6E: apiLevel >= 31, // Android 12.0+
        hasWiFi7: apiLevel >= 33, // Android 13.0+
        hasBluetooth5: apiLevel >= 28, // Android 9.0+
        hasBluetooth5_1: apiLevel >= 30, // Android 11.0+
        hasBluetooth5_2: apiLevel >= 31, // Android 12.0+
        hasBluetooth5_3: apiLevel >= 33, // Android 13.0+
        hasUWB: apiLevel >= 31, // Android 12.0+
        hasNFCTypeA: true,
        hasNFCTypeB: true,
        hasNFCTypeF: true,
        hasNFCTypeV: true,
        hasNFCIsoDep: true,
        hasNFCNdef: true,
        hasNFCNdefFormatable: true,
        hasNFCAbi: true,
        hasMifareClassic: false, // Device specific
        hasMifareUltralight: false, // Device specific
        hasMifareDesfire: false, // Device specific
        hasFingerprint: true,
        hasFaceUnlock: apiLevel >= 29, // Android 10.0+
        hasIris: false, // Device specific
        hasVoiceUnlock: true,
        hasSmartLock: apiLevel >= 21, // Android 5.0+
        hasTrustAgents: apiLevel >= 21, // Android 5.0+
        hasDevicePolicyManager: true,
        hasKeyguardManager: true,
        hasFingerprintManager: apiLevel >= 23, // Android 6.0+
        hasBiometricPrompt: apiLevel >= 28, // Android 9.0+
        hasCredentialManager: apiLevel >= 34, // Android 14.0+
        hasAppOpsManager: true,
        hasActivityManager: true,
        hasPackageManager: true,
        hasWindowManager: true,
        hasDisplayManager: true,
        hasInputMethodManager: true,
        hasAccessibilityManager: true,
        hasNotificationManager: true,
        hasAccountManager: true,
        hasDownloadManager: true,
        hasConnectivityManager: true,
        hasNsdManager: true,
        hasWifiP2pManager: true,
        hasBluetoothAdapter: true,
        hasNfcAdapter: true,
        hasSensorManager: true,
        hasLocationManager: true,
        hasCameraManager: true,
        hasAudioManager: true,
        hasTelephonyManager: true,
        hasSubscriptionManager: true,
        hasSmsManager: true,
        hasBluetoothManager: true,
        hasWifiManager: true,
        hasNfcManager: true,
        hasVibrator: true,
        hasFlashlight: true,
        hasBiometricPrompt: true,
        hasCredentialManager: true,
        hasKeyguardManager: true,
        hasDevicePolicyManager: true,
        hasAppOpsManager: true,
        hasActivityManager: true,
        hasPackageManager: true,
        hasWindowManager: true,
        hasDisplayManager: true,
        hasInputMethodManager: true,
        hasAccessibilityManager: true,
        hasNotificationManager: true,
        hasAccountManager: true,
        hasDownloadManager: true,
        hasConnectivityManager: true,
        hasNsdManager: true,
        hasWifiP2pManager: true,
      },
    };
  } catch (error) {
    console.error('Failed to get Android capabilities:', error);
    return {
      model: 'Unknown',
      brand: 'Unknown',
      systemVersion: 'Unknown',
      appVersion: 'Unknown',
      buildNumber: 'Unknown',
      isTablet: false,
      isEmulator: false,
      androidId: 'Unknown',
      apiLevel: 0,
      features: ANDROID_FEATURES,
      performance: {
        hasNeuralProcessingUnit: false,
        hasTensorFlowLite: false,
        hasMLKit: false,
        hasARCore: false,
        has5G: false,
        hasWiFi6: false,
        hasBluetooth5: false,
        hasNFC: false,
        hasFingerprint: false,
        hasFaceUnlock: false,
        hasGPS: false,
        hasAccelerometer: false,
        hasGyroscope: false,
        hasMagnetometer: false,
        hasLightSensor: false,
        hasProximitySensor: false,
        hasBarometer: false,
        hasTemperatureSensor: false,
        hasHumiditySensor: false,
        hasHeartRateSensor: false,
        hasStepCounter: false,
        hasStepDetector: false,
        hasGameRotationVector: false,
        hasGeomagneticRotationVector: false,
        hasRotationVector: false,
        hasLinearAcceleration: false,
        hasGravity: false,
        hasOrientation: false,
        hasPressure: false,
        hasRelativeHumidity: false,
        hasAmbientTemperature: false,
        hasMagneticFieldUncalibrated: false,
        hasGyroscopeUncalibrated: false,
        hasGameRotationVector: false,
        hasSignificantMotion: false,
        hasStepDetector: false,
        hasStepCounter: false,
        hasGeomagneticRotationVector: false,
        hasHeartRate: false,
        hasPose6dof: false,
        hasStationaryDetect: false,
        hasMotionDetect: false,
        hasHeartBeat: false,
        hasLowLatencyOffload: false,
        hasAccelerometerUncalibrated: false,
        hasHingeAngle: false,
        hasHeadTracker: false,
        hasAccelerometerLimitedAxes: false,
        hasGyroscopeLimitedAxes: false,
        hasHeading: false,
        hasCamera: false,
        hasFlash: false,
        hasFrontCamera: false,
        hasRearCamera: false,
        hasMicrophone: false,
        hasSpeaker: false,
        hasVibrator: false,
        hasFlashlight: false,
        hasGPS: false,
        hasNetworkLocation: false,
        hasPassiveLocation: false,
        hasWiFi: false,
        hasBluetooth: false,
        hasNFC: false,
        hasUSB: false,
        hasHDMI: false,
        hasEthernet: false,
        hasVPN: false,
        hasHotspot: false,
        hasTethering: false,
        hasTelephony: false,
        hasSMS: false,
        hasMMS: false,
        hasPhoneCalls: false,
        hasVideoCalls: false,
        hasVoLTE: false,
        hasVoWiFi: false,
        hasRCS: false,
        has5G: false,
        hasWiFi6: false,
        hasWiFi6E: false,
        hasWiFi7: false,
        hasBluetooth5: false,
        hasBluetooth5_1: false,
        hasBluetooth5_2: false,
        hasBluetooth5_3: false,
        hasUWB: false,
        hasNFCTypeA: false,
        hasNFCTypeB: false,
        hasNFCTypeF: false,
        hasNFCTypeV: false,
        hasNFCIsoDep: false,
        hasNFCNdef: false,
        hasNFCNdefFormatable: false,
        hasNFCAbi: false,
        hasMifareClassic: false,
        hasMifareUltralight: false,
        hasMifareDesfire: false,
        hasFingerprint: false,
        hasFaceUnlock: false,
        hasIris: false,
        hasVoiceUnlock: false,
        hasSmartLock: false,
        hasTrustAgents: false,
        hasDevicePolicyManager: false,
        hasKeyguardManager: false,
        hasFingerprintManager: false,
        hasBiometricPrompt: false,
        hasCredentialManager: false,
        hasAppOpsManager: false,
        hasActivityManager: false,
        hasPackageManager: false,
        hasWindowManager: false,
        hasDisplayManager: false,
        hasInputMethodManager: false,
        hasAccessibilityManager: false,
        hasNotificationManager: false,
        hasAccountManager: false,
        hasDownloadManager: false,
        hasConnectivityManager: false,
        hasNsdManager: false,
        hasWifiP2pManager: false,
        hasBluetoothAdapter: false,
        hasNfcAdapter: false,
        hasSensorManager: false,
        hasLocationManager: false,
        hasCameraManager: false,
        hasAudioManager: false,
        hasTelephonyManager: false,
        hasSubscriptionManager: false,
        hasSmsManager: false,
        hasBluetoothManager: false,
        hasWifiManager: false,
        hasNfcManager: false,
        hasVibrator: false,
        hasFlashlight: false,
        hasBiometricPrompt: false,
        hasCredentialManager: false,
        hasKeyguardManager: false,
        hasDevicePolicyManager: false,
        hasAppOpsManager: false,
        hasActivityManager: false,
        hasPackageManager: false,
        hasWindowManager: false,
        hasDisplayManager: false,
        hasInputMethodManager: false,
        hasAccessibilityManager: false,
        hasNotificationManager: false,
        hasAccountManager: false,
        hasDownloadManager: false,
        hasConnectivityManager: false,
        hasNsdManager: false,
        hasWifiP2pManager: false,
      },
    };
  }
}

// Android-specific optimizations
export function getAndroidOptimizations() {
  return {
    useTensorFlowLite: true,
    useMLKit: true,
    useNNAPI: true,
    useRenderScript: true,
    useVulkan: true,
    useOpenGLES: true,
    useOpenSL: true,
    useMediaCodec: true,
    useCamera2: true,
    useLocationServices: true,
    useGooglePlayServices: true,
    useFirebase: true,
    useGoogleMaps: true,
    useGoogleSignIn: true,
    useInAppUpdates: true,
    useInAppReviews: true,
    useBilling: true,
    useWorkManager: true,
    useJobScheduler: true,
    useAlarmManager: true,
    useForegroundService: true,
    useBackgroundService: true,
    useNotificationChannels: true,
    useDirectBoot: true,
    useDozeMode: true,
    useAppStandby: true,
    useBatteryOptimization: true,
    useMemoryOptimization: true,
    useStorageOptimization: true,
    useNetworkOptimization: true,
    useThermalOptimization: true,
    usePowerManager: true,
    useBatteryManager: true,
    useMemoryManager: true,
    useStorageManager: true,
    useNetworkManager: true,
    useLocationManager: true,
    useSensorManager: true,
    useCameraManager: true,
    useAudioManager: true,
    useTelephonyManager: true,
    useSubscriptionManager: true,
    useSmsManager: true,
    useBluetoothManager: true,
    useWifiManager: true,
    useNfcManager: true,
    useVibrator: true,
    useFlashlight: true,
    useBiometricPrompt: true,
    useCredentialManager: true,
    useKeyguardManager: true,
    useDevicePolicyManager: true,
    useAppOpsManager: true,
    useActivityManager: true,
    usePackageManager: true,
    useWindowManager: true,
    useDisplayManager: true,
    useInputMethodManager: true,
    useAccessibilityManager: true,
    useNotificationManager: true,
    useAccountManager: true,
    useDownloadManager: true,
    useConnectivityManager: true,
    useNsdManager: true,
    useWifiP2pManager: true,
  };
}

// Android-specific permissions
export const ANDROID_PERMISSIONS = [
  'camera',
  'microphone',
  'read_external_storage',
  'write_external_storage',
  'access_fine_location',
  'access_coarse_location',
  'read_contacts',
  'write_contacts',
  'read_phone_state',
  'call_phone',
  'read_call_log',
  'write_call_log',
  'add_voicemail',
  'use_sip',
  'process_outgoing_calls',
  'read_sms',
  'receive_sms',
  'send_sms',
  'receive_wap_push',
  'receive_mms',
  'read_cell_broadcasts',
  'body_sensors',
  'body_sensors_background',
  'activity_recognition',
  'record_audio',
  'read_calendar',
  'write_calendar',
  'access_notification_policy',
  'access_media_location',
  'access_background_location',
  'manage_external_storage',
  'access_media_location',
  'answer_phone_calls',
  'accept_handover',
  'bind_carrier_services',
  'bind_instant_service',
  'bind_midi_device_service',
  'bind_nfc_service',
  'bind_notification_listener_service',
  'bind_print_service',
  'bind_quick_settings_tile',
  'bind_remoteviews',
  'bind_screening_service',
  'bind_telecom_connection_service',
  'bind_text_service',
  'bind_tv_input_service',
  'bind_visual_voice_mail_service',
  'bind_vpn_service',
  'bind_vr_listener_service',
  'bind_wallpaper',
  'change_network_state',
  'change_wifi_multicast_state',
  'change_wifi_state',
  'clear_app_cache',
  'control_location_updates',
  'delete_cache_files',
  'delete_packages',
  'diagnostic',
  'disable_keyguard',
  'dump',
  'expand_status_bar',
  'factory_test',
  'foreground_service',
  'get_accounts',
  'get_accounts_privileged',
  'get_package_size',
  'global_search',
  'install_location_provider',
  'install_packages',
  'install_shortcut',
  'internet',
  'kill_background_processes',
  'location_hardware',
  'manage_documents',
  'master_clear',
  'media_content_control',
  'modify_audio_settings',
  'modify_phone_state',
  'mount_format_filesystems',
  'mount_unmount_filesystems',
  'nfc',
  'nfc_transaction_event',
  'package_usage_stats',
  'persistent_activity',
  'process_incoming_calls',
  'query_all_packages',
  'read_install_sessions',
  'read_network_usage_history',
  'read_phone_numbers',
  'read_privileged_phone_state',
  'read_sync_settings',
  'read_sync_stats',
  'read_voicemail',
  'reboot',
  'receive_boot_completed',
  'request_delete_packages',
  'request_ignore_battery_optimizations',
  'request_install_packages',
  'request_password_complexity',
  'restart_packages',
  'run_in_background',
  'schedule_exact_alarm',
  'set_alarm',
  'set_always_finish_activities',
  'set_animation_scale',
  'set_debug_app',
  'set_process_limit',
  'set_time',
  'set_time_zone',
  'set_wallpaper',
  'set_wallpaper_hints',
  'signal_persistent_processes',
  'status_bar',
  'system_alert_window',
  'transmit_ir',
  'uninstall_shortcut',
  'update_device_stats',
  'use_biometric',
  'use_fingerprint',
  'use_full_screen_intent',
  'vibrate',
  'wake_lock',
  'write_apn_settings',
  'write_gservices',
  'write_secure_settings',
  'write_settings',
  'write_sync_settings',
  'write_voicemail',
];

// Android-specific UI constants
export const ANDROID_UI = {
  statusBarHeight: 24,
  navigationBarHeight: 48,
  tabBarHeight: 56,
  safeAreaInsets: {
    top: 24,
    bottom: 0,
    left: 0,
    right: 0,
  },
  cornerRadius: 8,
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  typography: {
    fontFamily: 'Roboto',
    fontSize: {
      xs: 12,
      sm: 14,
      md: 16,
      lg: 18,
      xl: 20,
      xxl: 24,
      xxxl: 32,
    },
  },
  colors: {
    primary: '#2196F3',
    secondary: '#9C27B0',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#03A9F4',
    light: '#F5F5F5',
    dark: '#212121',
    background: '#FFFFFF',
    surface: '#F5F5F5',
    border: '#E0E0E0',
    text: '#212121',
    textSecondary: '#757575',
    placeholder: '#9E9E9E',
  },
};

// Android-specific performance settings
export const ANDROID_PERFORMANCE = {
  animationDuration: 0.3,
  transitionDuration: 0.25,
  maxConcurrentOperations: 4,
  memoryWarningThreshold: 0.85,
  batteryOptimizationEnabled: true,
  lowPowerModeOptimization: true,
  thermalStateOptimization: true,
  backgroundTaskTimeout: 600, // seconds
  networkTimeout: 35, // seconds
  cacheSizeLimit: 150, // MB
  imageCacheSizeLimit: 75, // MB
  videoCacheSizeLimit: 300, // MB
};