/**
 * iOS-specific utilities for Bharat AI SDK
 */

import { Platform } from 'react-native';
import DeviceInfo from 'react-native-device-info';

// iOS-specific constants
export const IOS_VERSION = Platform.Version as number;
export const IS_IOS = Platform.OS === 'ios';

// iOS-specific features
export const IOS_FEATURES = {
  faceId: true,
  touchId: true,
  siri: true,
  applePay: true,
  healthKit: true,
  homeKit: true,
  arKit: true,
  carPlay: true,
  watchConnectivity: true,
  cloudKit: true,
  passKit: true,
  coreMotion: true,
  coreLocation: true,
  coreBluetooth: true,
  coreNFC: true,
  userNotifications: true,
  backgroundTasks: true,
  widgetKit: true,
  appClip: true,
  sfSymbols: true,
  coreML: true,
  createML: true,
  vision: true,
  naturalLanguage: true,
  speech: true,
  soundAnalysis: true,
  pencilKit: true,
  fileProvider: true,
  coreHaptics: true,
  coreSpotlight: true,
  coreData: true,
  cloudDocuments: true,
  multipeerConnectivity: true,
  externalAccessory: true,
  networkExtension: true,
  replayKit: true,
  screenTime: true,
  familyControls: true,
  deviceCheck: true,
  appAttest: true,
  cryptoKit: true,
  authenticationServices: true,
  localAuthentication: true,
  linkPresentation: true,
  messageUI: true,
  safariServices: true,
  storeKit: true,
  iAd: true,
  adSupport: true,
  coreTelephony: true,
  coreText: true,
  coreGraphics: true,
  coreAnimation: true,
  coreImage: true,
  avFoundation: true,
  coreAudio: true,
  coreMedia: true,
  coreVideo: true,
  metal: true,
  metalKit: true,
  metalPerformanceShaders: true,
  accelerate: true,
  simd: true,
  compression: true,
  gameController: true,
  gameKit: true,
  sceneKit: true,
  spriteKit: true,
  coreMotion: true,
  coreLocation: true,
  mapKit: true,
  coreBluetooth: true,
  coreNFC: true,
  eventKit: true,
  contacts: true,
  photos: true,
  photosUI: true,
  phphotoLibrary: true,
  avkit: true,
  mediatoolbox: true,
  coreHaptics: true,
  puckit: true,
  callKit: true,
  pushKit: true,
  userNotifications: true,
  backgroundTasks: true,
  widgetKit: true,
  appClip: true,
  coreSpotlight: true,
  coreData: true,
  cloudKit: true,
  coreML: true,
  createML: true,
  vision: true,
  naturalLanguage: true,
  speech: true,
  soundAnalysis: true,
  pencilKit: true,
  fileProvider: true,
  coreHaptics: true,
  coreSpotlight: true,
  coreData: true,
  cloudDocuments: true,
  multipeerConnectivity: true,
  externalAccessory: true,
  networkExtension: true,
  replayKit: true,
  screenTime: true,
  familyControls: true,
  deviceCheck: true,
  appAttest: true,
  cryptoKit: true,
  authenticationServices: true,
  localAuthentication: true,
  linkPresentation: true,
  messageUI: true,
  safariServices: true,
  storeKit: true,
  iAd: true,
  adSupport: true,
  coreTelephony: true,
  coreText: true,
  coreGraphics: true,
  coreAnimation: true,
  coreImage: true,
  avFoundation: true,
  coreAudio: true,
  coreMedia: true,
  coreVideo: true,
  metal: true,
  metalKit: true,
  metalPerformanceShaders: true,
  accelerate: true,
  simd: true,
  compression: true,
  gameController: true,
  gameKit: true,
  sceneKit: true,
  spriteKit: true,
};

// iOS-specific device capabilities
export async function getIOSCapabilities() {
  try {
    const model = await DeviceInfo.getModel();
    const systemVersion = await DeviceInfo.getSystemVersion();
    const appVersion = DeviceInfo.getVersion();
    const buildNumber = DeviceInfo.getBuildNumber();
    const isTablet = DeviceInfo.isTablet();
    const isEmulator = await DeviceInfo.isEmulator();

    return {
      model,
      systemVersion,
      appVersion,
      buildNumber,
      isTablet,
      isEmulator,
      features: IOS_FEATURES,
      performance: {
        hasA12Bionic: model.includes('iPhone X') || model.includes('iPhone 11') || model.includes('iPhone 12'),
        hasA13Bionic: model.includes('iPhone 11') || model.includes('iPhone SE'),
        hasA14Bionic: model.includes('iPhone 12'),
        hasA15Bionic: model.includes('iPhone 13'),
        hasA16Bionic: model.includes('iPhone 14'),
        hasM1: model.includes('iPad Pro') && parseInt(systemVersion.split('.')[0]) >= 14,
        hasM2: model.includes('iPad Pro') && parseInt(systemVersion.split('.')[0]) >= 16,
        supports5G: model.includes('iPhone 12') || model.includes('iPhone 13') || model.includes('iPhone 14'),
        supportsFaceID: model.includes('iPhone X') || model.includes('iPhone 11') || model.includes('iPhone 12') || model.includes('iPhone 13') || model.includes('iPhone 14'),
        supportsTouchID: model.includes('iPhone 8') || model.includes('iPhone SE'),
        supportsApplePencil: model.includes('iPad Pro') || model.includes('iPad Air') || model.includes('iPad mini'),
        supportsMagicKeyboard: model.includes('iPad Pro'),
        supportsAppleWatch: true,
        supportsAirPods: true,
        supportsAirPlay: true,
        supportsCarPlay: true,
        supportsHomeKit: true,
        supportsHealthKit: true,
        supportsARKit: true,
        supportsCoreML: true,
        supportsMetal: true,
        supportsMetalKit: true,
        supportsMetalPerformanceShaders: true,
        supportsAccelerate: true,
        supportsCoreMotion: true,
        supportsCoreLocation: true,
        supportsCoreBluetooth: true,
        supportsCoreNFC: true,
        supportsEventKit: true,
        supportsContacts: true,
        supportsPhotos: true,
        supportsPhotosUI: true,
        supportsAVFoundation: true,
        supportsCoreAudio: true,
        supportsCoreMedia: true,
        supportsCoreVideo: true,
        supportsGameController: true,
        supportsGameKit: true,
        supportsSceneKit: true,
        supportsSpriteKit: true,
        supportsCoreHaptics: true,
        supportsPencilKit: true,
        supportsFileProvider: true,
        supportsCoreSpotlight: true,
        supportsCoreData: true,
        supportsCloudKit: true,
        supportsMultipeerConnectivity: true,
        supportsExternalAccessory: true,
        supportsNetworkExtension: true,
        supportsReplayKit: true,
        supportsScreenTime: true,
        supportsFamilyControls: true,
        supportsDeviceCheck: true,
        supportsAppAttest: true,
        supportsCryptoKit: true,
        supportsAuthenticationServices: true,
        supportsLocalAuthentication: true,
        supportsLinkPresentation: true,
        supportsMessageUI: true,
        supportsSafariServices: true,
        supportsStoreKit: true,
        supportsCoreTelephony: true,
        supportsCoreText: true,
        supportsCoreGraphics: true,
        supportsCoreAnimation: true,
        supportsCoreImage: true,
        supportsAVKit: true,
        supportsMediaToolbox: true,
        supportsCompression: true,
      },
    };
  } catch (error) {
    console.error('Failed to get iOS capabilities:', error);
    return {
      model: 'Unknown',
      systemVersion: 'Unknown',
      appVersion: 'Unknown',
      buildNumber: 'Unknown',
      isTablet: false,
      isEmulator: false,
      features: IOS_FEATURES,
      performance: {
        hasA12Bionic: false,
        hasA13Bionic: false,
        hasA14Bionic: false,
        hasA15Bionic: false,
        hasA16Bionic: false,
        hasM1: false,
        hasM2: false,
        supports5G: false,
        supportsFaceID: false,
        supportsTouchID: false,
        supportsApplePencil: false,
        supportsMagicKeyboard: false,
        supportsAppleWatch: false,
        supportsAirPods: false,
        supportsAirPlay: false,
        supportsCarPlay: false,
        supportsHomeKit: false,
        supportsHealthKit: false,
        supportsARKit: false,
        supportsCoreML: false,
        supportsMetal: false,
        supportsMetalKit: false,
        supportsMetalPerformanceShaders: false,
        supportsAccelerate: false,
        supportsCoreMotion: false,
        supportsCoreLocation: false,
        supportsCoreBluetooth: false,
        supportsCoreNFC: false,
        supportsEventKit: false,
        supportsContacts: false,
        supportsPhotos: false,
        supportsPhotosUI: false,
        supportsAVFoundation: false,
        supportsCoreAudio: false,
        supportsCoreMedia: false,
        supportsCoreVideo: false,
        supportsGameController: false,
        supportsGameKit: false,
        supportsSceneKit: false,
        supportsSpriteKit: false,
        supportsCoreHaptics: false,
        supportsPencilKit: false,
        supportsFileProvider: false,
        supportsCoreSpotlight: false,
        supportsCoreData: false,
        supportsCloudKit: false,
        supportsMultipeerConnectivity: false,
        supportsExternalAccessory: false,
        supportsNetworkExtension: false,
        supportsReplayKit: false,
        supportsScreenTime: false,
        supportsFamilyControls: false,
        supportsDeviceCheck: false,
        supportsAppAttest: false,
        supportsCryptoKit: false,
        supportsAuthenticationServices: false,
        supportsLocalAuthentication: false,
        supportsLinkPresentation: false,
        supportsMessageUI: false,
        supportsSafariServices: false,
        supportsStoreKit: false,
        supportsCoreTelephony: false,
        supportsCoreText: false,
        supportsCoreGraphics: false,
        supportsCoreAnimation: false,
        supportsCoreImage: false,
        supportsAVKit: false,
        supportsMediaToolbox: false,
        supportsCompression: false,
      },
    };
  }
}

// iOS-specific optimizations
export function getIOSOptimizations() {
  return {
    useCoreML: true,
    useMetal: true,
    useAccelerate: true,
    useCoreAnimation: true,
    useCoreGraphics: true,
    useCoreImage: true,
    useAVFoundation: true,
    useCoreAudio: true,
    useCoreMedia: true,
    useCoreVideo: true,
    useCoreMotion: true,
    useCoreLocation: true,
    useCoreBluetooth: true,
    useCoreNFC: true,
    useEventKit: true,
    useContacts: true,
    usePhotos: true,
    usePhotosUI: true,
    useGameController: true,
    useGameKit: true,
    useSceneKit: true,
    useSpriteKit: true,
    useCoreHaptics: true,
    usePencilKit: true,
    useFileProvider: true,
    useCoreSpotlight: true,
    useCoreData: true,
    useCloudKit: true,
    useMultipeerConnectivity: true,
    useExternalAccessory: true,
    useNetworkExtension: true,
    useReplayKit: true,
    useScreenTime: true,
    useFamilyControls: true,
    useDeviceCheck: true,
    useAppAttest: true,
    useCryptoKit: true,
    useAuthenticationServices: true,
    useLocalAuthentication: true,
    useLinkPresentation: true,
    useMessageUI: true,
    useSafariServices: true,
    useStoreKit: true,
    useCoreTelephony: true,
    useCoreText: true,
    useCompression: true,
    useMetalPerformanceShaders: true,
    use simd: true,
  };
}

// iOS-specific permissions
export const IOS_PERMISSIONS = [
  'camera',
  'microphone',
  'photo_library',
  'contacts',
  'location',
  'notifications',
  'calendar',
  'reminders',
  'bluetooth',
  'motion',
  'health',
  'home',
  'siri',
  'face_id',
  'touch_id',
  'user_tracking',
  'app_tracking_transparency',
];

// iOS-specific UI constants
export const IOS_UI = {
  statusBarHeight: 44,
  navigationBarHeight: 44,
  tabBarHeight: 83,
  safeAreaInsets: {
    top: 44,
    bottom: 34,
    left: 0,
    right: 0,
  },
  cornerRadius: 8,
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  typography: {
    fontFamily: 'San Francisco',
    fontSize: {
      xs: 12,
      sm: 14,
      md: 16,
      lg: 18,
      xl: 20,
      xxl: 24,
      xxxl: 32,
    },
  },
  colors: {
    primary: '#007AFF',
    secondary: '#5856D6',
    success: '#34C759',
    warning: '#FF9500',
    error: '#FF3B30',
    info: '#5AC8FA',
    light: '#F2F2F7',
    dark: '#1C1C1E',
    background: '#FFFFFF',
    surface: '#F2F2F7',
    border: '#C6C6C8',
    text: '#000000',
    textSecondary: '#8E8E93',
    placeholder: '#C7C7CC',
  },
};

// iOS-specific performance settings
export const IOS_PERFORMANCE = {
  animationDuration: 0.3,
  transitionDuration: 0.25,
  maxConcurrentOperations: 6,
  memoryWarningThreshold: 0.8,
  batteryOptimizationEnabled: true,
  lowPowerModeOptimization: true,
  thermalStateOptimization: true,
  backgroundTaskTimeout: 180, // seconds
  networkTimeout: 30, // seconds
  cacheSizeLimit: 100, // MB
  imageCacheSizeLimit: 50, // MB
  videoCacheSizeLimit: 200, // MB
};